name: swap
description: Server side rendering for Flutter core models.
version: 0.0.2-dev.3
homepage: https://github.com/Flutter-Swap/dart

environment:
  sdk: ^3.3.0

dependencies:
  meta: ^1.10.0
  vector_math: ^2.1.4

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
