name: swap_server_sample
description: A Swap server sample.
version: 1.0.0

environment:
  sdk: ^3.3.0

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_swap: ^0.0.1-dev

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
