name: shelf_swap
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.2.3

dependencies:
  shelf: ^1.4.1
  swap:

dependency_overrides:
  swap:
    path: ../swap

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
